accent = "#0073ff"
cursor = "#00ff73"
foreground = "#00f7f7"
background = "#0d0d1a"
selection_foreground = "#ffcc00"
selection_background = "#ff0099"

color0 = "#212130"
color1 = "#ff0099"
color2 = "#00ff73"
color3 = "#ffcc00"
color4 = "#0073ff"
color5 = "#ff00ff"
color6 = "#00ffff"
color7 = "#99aab5"
color8 = "#36364a"
color9 = "#ff33b3"
color10 = "#33ff99"
color11 = "#ffeb4c"
color12 = "#3399ff"
color13 = "#ff33ff"
color14 = "#33ffff"
color15 = "#c3d6e5"
