
foreground                      #00f7f7

background                      #0d0d1a

selection_foreground            #ffcc00

selection_background            #ff0099


cursor                          #00ff73

cursor_text_color               #36364a


url_color                       #0073ff


active_border_color             #ff33b3

inactive_border_color           #555566

bell_border_color               #ff0099
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_background           #212130

active_tab_foreground           #00f7f7

inactive_tab_background         #0d0d1a

inactive_tab_foreground         #99aab5

tab_bar_background              #0d0d1a
tab_bar_margin_color            none

mark1_foreground                #0d0d1a
mark1_background                #00ffff
mark2_foreground                #0d0d1a
mark2_background                #ffcc00
mark3_foreground                #0d0d1a
mark3_background                #ff00ff


color0                          #36364a

color8                          #555566

color1                          #ff0099

color9                          #ff33b3

color2                          #00ff73

color10                         #33ff99


color3                          #ffcc00

color11                         #ffeb4c

color4                          #0073ff

color12                         #3399ff


color5                          #ff00ff

color13                         #ff33ff


color6                          #00ffff

color14                         #33ffff

color7                          #99aab5

color15                         #c3d6e5